# Generated by Django 2.0.4 on 2018-04-25 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Story', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter Location Name', max_length=200)),
                ('story', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Story.Story')),
            ],
        ),
    ]
