# Generated by Django 2.0.4 on 2018-04-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Story', '0004_locationneighbors'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='logoFileName',
            field=models.CharField(help_text='Enter Image Location', max_length=200, null=True),
        ),
    ]
