# Generated by Django 2.0.4 on 2018-05-01 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Story', '0005_story_logofilename'),
    ]

    operations = [
        migrations.AddField(
            model_name='characters',
            name='imageFileName',
            field=models.CharField(help_text='Enter logo file name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='characters',
            name='story',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Story.Story'),
        ),
    ]
