# Generated by Django 2.0.4 on 2018-05-06 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Story', '0007_auto_20180501_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='characters',
            name='dialougueOne',
            field=models.CharField(help_text='Enter Dialougue', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='characters',
            name='dialougueThree',
            field=models.CharField(help_text='Enter Dialougue', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='characters',
            name='dialougueTwo',
            field=models.CharField(help_text='Enter Dialougue', max_length=200, null=True),
        ),
    ]
