# Generated by Django 2.0.4 on 2018-05-07 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Story', '0008_auto_20180506_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='characters',
            name='answerOne',
            field=models.CharField(help_text='Enter Answer', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='characters',
            name='dialougueOne',
            field=models.CharField(help_text='Enter Dialougue', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='characters',
            name='dialougueThree',
            field=models.CharField(help_text='Enter Dialougue', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='characters',
            name='dialougueTwo',
            field=models.CharField(help_text='Enter Dialougue', max_length=500, null=True),
        ),
    ]
