# Generated by Django 2.0.4 on 2018-05-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Story', '0009_auto_20180507_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='characters',
            name='answerThree',
            field=models.CharField(help_text='Enter Answer', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='characters',
            name='answerTwo',
            field=models.CharField(help_text='Enter Answer', max_length=500, null=True),
        ),
    ]
